#!/bin/bash

if [ ! -f ~/.vimrc ]; then
	ln -s `pwd`/vim/.vimrc ~/.vimrc
fi

if [ ! -f ~/.tmux.conf ]; then
	ln -s `pwd`/tmux/.tmux.conf ~/.tmux.conf
fi

if [ ! -f ~/.bash_profile ] && [ -f ~/.zshrc ]; then
	ln -s `pwd`/bash/.bash_profile ~/.bash_profile
echo "
if [ -f ~/.bash_profile ]; then 
    . ~/.bash_profile 
fi" >> ~/.zshrc
fi

    
